vscode:
  extensions:
    # Go related extensions (lint, fmt, ...)
    - golang.Go                   # https://marketplace.visualstudio.com/items?itemName=golang.Go
    # TODO (hmny) check out this one ==>  - premparihar.gotestexplorer
    
    # Git & GitHub related extensions
    - eamodio.gitlens             # https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens
    - mhutchie.git-graph          # https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph
    
    # Utilities and project managment
    - Gruntfuggly.todo-tree       # https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree
    - aaron-bond.better-comments  # https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments

# ? This may be not necessary right now
# ?  tasks:
# ?    - name: GitPod container setup
# ?      command: .gitpod/setup.sh